# Generated by Django 3.1 on 2020-11-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='objet',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
