# Generated by Django 3.1.6 on 2021-02-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_client_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
